name: "🐛 Bug Report"
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out as much detail as possible to help us investigate.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing issue for this?
      description: Please search existing issues before creating a new one.
      options:
        - label: I have searched the existing issues and none match my bug report.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal code snippet or a step-by-step list to reproduce the issue.
      placeholder: |
        1. Import package '...'
        2. Call function '...'
        3. Pass argument '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: If applicable, provide a minimal reproducible code snippet.
      render: go
      placeholder: |
        package main

        import "fmt"

        func main() {
            // your code here
        }

  - type: textarea
    id: error-output
    attributes:
      label: Error Output / Logs
      description: If applicable, paste any relevant error messages or log output.
      render: shell

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: "Output of `go version`"
      placeholder: "e.g., go1.22.0"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module/Package Version
      description: "Version of this module you are using"
      placeholder: "e.g., v1.2.3"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Specific OS version"
      placeholder: "e.g., Ubuntu 22.04, macOS 14.2, Windows 11"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here.
