name: "📝 Documentation Improvement"
description: Report missing, incorrect, or unclear documentation
title: "[DOCS]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please provide details about what needs to be updated.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - Code comments / GoDoc
        - Examples / Tutorials
        - API Reference
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect / outdated documentation
        - Unclear / confusing documentation
        - Typo / grammatical error
        - Missing code examples
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what documentation is missing, incorrect, or unclear.
      placeholder: Provide details about the documentation issue...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: "Where is the documentation issue? Provide a file path, URL, or section name."
      placeholder: "e.g., README.md, docs/getting-started.md, or a URL"

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: If you have a suggestion for how to fix or improve the documentation, describe it here.
      placeholder: Describe the improvement...

  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to submit a PR to improve this documentation?
      options:
        - label: I would be willing to submit a PR to improve this documentation.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
