package textutils

//goland:noinspection GoUnusedConst
const (
	// AUpperChar = 'A'
	AUpperChar = 'A'
	// ALowerChar = 'a'
	ALowerChar = 'a'
	// BUpperChar = 'B'
	BUpperChar = 'B'
	// BLowerChar = 'b'
	BLowerChar = 'b'
	// CUpperChar = 'C'
	CUpperChar = 'C'
	// CLowerChar = 'c'
	CLowerChar = 'c'
	// DUpperChar = 'D'
	DUpperChar = 'D'
	// DLowerChar = 'd'
	DLowerChar = 'd'
	// EUpperChar = 'E'
	EUpperChar = 'E'
	// ELowerChar = 'e'
	ELowerChar = 'e'
	// FUpperChar = 'F'
	FUpperChar = 'F'
	// FLowerChar = 'f'
	FLowerChar = 'f'
	// GUpperChar = 'G'
	GUpperChar = 'G'
	// GLowerChar = 'g'
	GLowerChar = 'g'
	// HUpperChar = 'H'
	HUpperChar = 'H'
	// HLowerChar = 'h'
	HLowerChar = 'h'
	// IUpperChar = 'I'
	IUpperChar = 'I'
	// ILowerChar = 'i'
	ILowerChar = 'i'
	// JUpperChar = 'J'
	JUpperChar = 'J'
	// JLowerChar = 'j'
	JLowerChar = 'j'
	// KUpperChar = 'K'
	KUpperChar = 'K'
	// KLowerChar = 'k'
	KLowerChar = 'k'
	// LUpperChar = 'L'
	LUpperChar = 'L'
	// LLowerChar = 'l'
	LLowerChar = 'l'
	// MUpperChar = 'M'
	MUpperChar = 'M'
	// MLowerChar = 'm'
	MLowerChar = 'm'
	// NUpperChar = 'N'
	NUpperChar = 'N'
	// NLowerChar = 'n'
	NLowerChar = 'n'
	// OUpperChar = 'O'
	OUpperChar = 'O'
	// OLowerChar = 'o'
	OLowerChar = 'o'
	// PUpperChar = 'P'
	PUpperChar = 'P'
	// PLowerChar = 'p'
	PLowerChar = 'p'
	// QUpperChar = 'Q'
	QUpperChar = 'Q'
	// QLowerChar = 'q'
	QLowerChar = 'q'
	// RUpperChar = 'R'
	RUpperChar = 'R'
	// RLowerChar = 'r'
	RLowerChar = 'r'
	// SUpperChar = 'S'
	SUpperChar = 'S'
	// SLowerChar = 's'
	SLowerChar = 's'
	// TUpperChar = 'T'
	TUpperChar = 'T'
	// TLowerChar = 't'
	TLowerChar = 't'
	// UUpperChar = 'U'
	UUpperChar = 'U'
	// ULowerChar = 'u'
	ULowerChar = 'u'
	// VUpperChar = 'V'
	VUpperChar = 'V'
	// VLowerChar = 'v'
	VLowerChar = 'v'
	// WUpperChar = 'W'
	WUpperChar = 'W'
	// WLowerChar = 'w'
	WLowerChar = 'w'
	// XUpperChar = 'X'
	XUpperChar = 'X'
	// XLowerChar = 'x'
	XLowerChar = 'x'
	// YUpperChar = 'Y'
	YUpperChar = 'Y'
	// YLowerChar = 'y'
	YLowerChar = 'y'
	// ZUpperChar = 'Z'
	ZUpperChar = 'Z'
	// ZLowerChar = 'z'
	ZLowerChar = 'z'
	// ColonChar  =':'
	ColonChar = ':'
	// SemiColonChar  =';'
	SemiColonChar = ';'
	// DoubleQuoteChar = '"'
	DoubleQuoteChar = '"'
	// SingleQuoteChar = '\''
	SingleQuoteChar = '\''
	// ForwardSlashChar  ='/'
	ForwardSlashChar = '/'
	// BackSlashChar = '\'
	BackSlashChar = '\\'
	// QuestionMarkChar  ='?'
	QuestionMarkChar = '?'
	// GreaterThanChar = '>'
	GreaterThanChar = '>'
	// LessThanChar  ='<'
	LessThanChar = '<'
	// PeriodChar = '.'
	PeriodChar = '.'
	// CommaChar  =','
	CommaChar = ','
	// OpenBraceChar = '{'
	OpenBraceChar = '{'
	// CloseBraceChar  ='}'
	CloseBraceChar = '}'
	// OpenBracketChar  = '['
	OpenBracketChar = '['
	// CloseBracketChar  = ']'
	CloseBracketChar = ']'
	// OpenParenthesesChar  = '('
	OpenParenthesesChar = '('
	// CloseParenthesesChar  = ')'
	CloseParenthesesChar = ')'
	// HyphenChar = '-'
	HyphenChar = '-'
	// UnderScoreChar  = '_'
	UnderScoreChar = '_'
	// PlusChar = '+'
	// PlusChar = '+'
	PlusChar = '+'
	// EqualChar  = '='
	EqualChar = '='
	// AsteriskChar  = '*'
	AsteriskChar = '*'
	// AmpersandChar = '&'
	AmpersandChar = '&'
	// CircumflexAccentChar  = '^'
	CircumflexAccentChar = '^'
	// PercentChar = '%'
	PercentChar = '%'
	// DollarChar = '$'
	DollarChar = '$'
	// HashChar = '#'
	HashChar = '#'
	// AtChar = '@'
	AtChar = '@'
	// ExclamationChar = '!'
	ExclamationChar = '!'
	// TildeChar  = '~'
	TildeChar = '~'
	// GraveAccentChar = '`'
	GraveAccentChar = '`'
	// PipeChar = '|'
	PipeChar = '|'
	//WhiteSpace char
	WhiteSpaceChar  = ' '
	NewLineChar     = '\n'
	CarriageRtnChar = '\r'

	// AUpperStr = "A"
	AUpperStr = "A"
	// ALowerStr = "a"
	ALowerStr = "a"
	// BUpperStr = "B"
	BUpperStr = "B"
	// BLowerStr = "b"
	BLowerStr = "b"
	// CUpperStr = "C"
	CUpperStr = "C"
	// CLowerStr = "c"
	CLowerStr = "c"
	// DUpperStr = "D"
	DUpperStr = "D"
	// DLowerStr = "d"
	DLowerStr = "d"
	// EUpperStr = "E"
	EUpperStr = "E"
	// ELowerStr = "e"
	ELowerStr = "e"
	// FUpperStr = "F"
	FUpperStr = "F"
	// FLowerStr = "f"
	FLowerStr = "f"
	// GUpperStr = "G"
	GUpperStr = "G"
	// GLowerStr = "g"
	GLowerStr = "g"
	// HUpperStr = "H"
	HUpperStr = "H"
	// HLowerStr = "h"
	HLowerStr = "h"
	// IUpperStr = "I"
	IUpperStr = "I"
	// ILowerStr = "i"
	ILowerStr = "i"
	// JUpperStr = "J"
	JUpperStr = "J"
	// JLowerStr = "j"
	JLowerStr = "j"
	// KUpperStr = "K"
	KUpperStr = "K"
	// KLowerStr = "k"
	KLowerStr = "k"
	// LUpperStr = "L"
	LUpperStr = "L"
	// LLowerStr = "l"
	LLowerStr = "l"
	// MUpperStr = "M"
	MUpperStr = "M"
	// MLowerStr = "m"
	MLowerStr = "m"
	// NUpperStr = "N"
	NUpperStr = "N"
	// NLowerStr = "n"
	NLowerStr = "n"
	// OUpperStr = "O"
	OUpperStr = "O"
	// OLowerStr = "o"
	OLowerStr = "o"
	// PUpperStr = "P"
	PUpperStr = "P"
	// PLowerStr = "p"
	PLowerStr = "p"
	// QUpperStr = "Q"
	QUpperStr = "Q"
	// QLowerStr = "q"
	QLowerStr = "q"
	// RUpperStr = "R"
	RUpperStr = "R"
	// RLowerStr = "r"
	RLowerStr = "r"
	// SUpperStr = "S"
	SUpperStr = "S"
	// SLowerStr = "s"
	SLowerStr = "s"
	// TUpperStr = "T"
	TUpperStr = "T"
	// TLowerStr = "t"
	TLowerStr = "t"
	// UUpperStr = "U"
	UUpperStr = "U"
	// ULowerStr = "u"
	ULowerStr = "u"
	// VUpperStr = "V"
	VUpperStr = "V"
	// VLowerStr = "v"
	VLowerStr = "v"
	// WUpperStr = "W"
	WUpperStr = "W"
	// WLowerStr = "w"
	WLowerStr = "w"
	// XUpperStr = "X"
	XUpperStr = "X"
	// XLowerStr = "x"
	XLowerStr = "x"
	// YUpperStr = "Y"
	YUpperStr = "Y"
	// YLowerStr = "y"
	YLowerStr = "y"
	// ZUpperStr = "Z"
	ZUpperStr = "Z"
	// ZLowerStr = "z"
	ZLowerStr = "z"
	// ColonStr  =":"
	ColonStr = ":"
	// SemiColonStr  =";"
	SemiColonStr = ";"
	// DoubleQuoteStr = "\""
	DoubleQuoteStr = "\""
	// SingleQuoteStr = """
	SingleQuoteStr = "\""
	// ForwardSlashStr  ="/"
	ForwardSlashStr = "/"
	// BackSlashStr = "/"
	BackSlashStr = "\\"
	// QuestionMarkStr  ="?"
	QuestionMarkStr = "?"
	// GreaterThanStr = ">"
	GreaterThanStr = ">"
	// LessThanStr  ="<"
	LessThanStr = "<"
	// PeriodStr = "."
	PeriodStr = "."
	// CommaStr  =","
	CommaStr = ","
	// OpenBraceStr = "{"
	OpenBraceStr = "{"
	// CloseBraceStr  ="}"
	CloseBraceStr = "}"
	// OpenBracketStr  = "["
	OpenBracketStr = "["
	// CloseBracketStr  = "]"
	CloseBracketStr = "]"
	// OpenParenthesisStr  = "("
	OpenParenthesisStr = "("
	// CloseParenthesisStr  = ")"
	CloseParenthesisStr = ")"
	// HyphenStr = "-"
	HyphenStr = "-"
	// UnderScoreStr  = "_"
	UnderScoreStr = "_"
	// PlusStr = "+"
	// PlusStr = "+"
	PlusStr = "+"
	// EqualStr  = "="
	EqualStr = "="
	// AsteriskStr  = "*"
	AsteriskStr = "*"
	// AmpersandStr = "&"
	AmpersandStr = "&"
	// CircumflexAccentStr  = "^"
	CircumflexAccentStr = "^"
	// PercentStr = "%"
	PercentStr = "%"
	// DollarStr = "$"
	DollarStr = "$"
	// HashStr = "#"
	HashStr = "#"
	// AtStr = "@"
	AtStr = "@"
	// ExclamationStr = "!"
	ExclamationStr = "!"
	// TildeStr  = "~"
	TildeStr = "~"
	// GraveAccentStr = "`"
	GraveAccentStr = "`"
	// PipeStr = "|"
	PipeStr = "|"
	// EmptyStr = ""
	EmptyStr = ""
	//WhiteSpace String
	WhiteSpaceStr = " "
	// NewLine String
	NewLineString = "\n"
	//Carriage Return String
	CarriageRtnString = "\r"
)
