name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  ci:
    uses: nandlabs/oss-workflows/.github/workflows/go-ci.yml@main
    with:
      go-versions: '["1.25", "1.26"]'
      coverage-go-version: "1.25"
