name: "Lint"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  lint:
    uses: nandlabs/oss-workflows/.github/workflows/go-lint.yml@main
    with:
      go-version: "1.25"
