name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: nandlabs/oss-workflows/.github/workflows/go-release.yml@main
    permissions:
      contents: write
    with:
      go-version: "1.25"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
